# Make Database Connection

In [1]:
from commandcast.data_manager import DataManager

db = DataManager(
    host='localhost',
    port=9000
)

# Ingest Data

In [2]:
import pandas as pd

df = pd.read_csv("data/m4.csv")
df.head()

df['ds'] = pd.to_datetime(df['ds'])
df.dtypes

# ID Columns 
ds_col = 'ds'
id_col = 'unique_id'

# Measurement Columns
measure_cols = list(df.drop(['ds', 'unique_id'], axis=1).columns)        

# Configure Dataset in Database
config = {
    'dataset_name' : 'M4_HOURLY', # Overall name of the timeseries dataset
    'feature_engineering': 'minimal',
    'ds_col' : ds_col, # Timeseries column
    'id_col' : id_col, # Identifier Unique to Timeseries,
    'hierarchy': [],
    'measure_cols': measure_cols
}

# Method to Create Tables and Ingest Data
db.create_dataset(config=config, df=df)

# Explore how to create time series featues

In [3]:
features = db.create_features(df, config=db.extract_config(config))
features.head()

Feature Extraction: 100%|██████████| 10/10 [00:00<00:00, 12.96it/s]


unique_id          time_begin            time_end  count dataset_name  \
0        T1 2015-07-01 12:00:00 2015-08-01 15:00:00    748    M4_HOURLY   
1       T10 2015-07-01 12:00:00 2015-08-01 15:00:00    748    M4_HOURLY   
2      T100 2015-07-01 12:00:00 2015-08-01 15:00:00    748    M4_HOURLY   
3      T101 2015-07-01 12:00:00 2015-08-01 15:00:00    748    M4_HOURLY   
4      T102 2015-07-01 12:00:00 2015-08-01 15:00:00    748    M4_HOURLY   

   values__sum_values  values__median  values__mean  values__length  \
0            478586.0           634.0    639.820856           748.0   
1            331441.0           442.0    443.102941           748.0   
2            753242.5           964.0   1007.008690           748.0   
3           1777609.0          2374.0   2376.482620           748.0   
4           1305922.0          1739.0   1745.885027           748.0   

   values__standard_deviation  values__variance  values__root_mean_square  \
0                  156.533479      24502.729939                658.690714   
1                   35.451199       1256.787531                444.518846   
2                  386.660351     149506.226863               1078.690284   
3                  247.417708      61215.522425               2389.327346   
4                  425.193520     180789.529562               1796.915150   

   values__maximum  values__absolute_maximum  values__minimum  
0            926.0                     926.0            349.0  
1            517.0                     517.0            336.0  
2           1875.0                    1875.0            351.0  
3           2992.0                    2992.0           1533.0  
4           2540.0                    2540.0            634.0

# Extract a time series from the database

In [8]:
id = 'T2'
features = db.get_features(id, table_name = config['dataset_name'] + "_meta")
print(features)
series = db.get_series(id, table_name = config['dataset_name'] + "_ts")
print(series)

  unique_id dataset_name                     time_end  count  \
0        T2    M4_HOURLY  2015-08-01T15:00:00.000000Z    748   

   values__sum_values  values__median  values__mean  values__length  \
0           1943707.0          2517.0    2598.53877           748.0   

   values__standard_deviation  values__variance  values__root_mean_square  \
0                  655.316397     429439.580048                2679.89614   

   values__maximum  values__absolute_maximum  values__minimum  \
0           4013.0                    4013.0           1466.0   

                     timestamp  
0  2015-07-01T12:00:00.000000Z  
     unique_id  values                           ds
0           T2  3124.0  2015-07-01T12:00:00.000000Z
1           T2  3124.0  2015-07-01T12:00:00.000000Z
2           T2  2990.0  2015-07-01T13:00:00.000000Z
3           T2  2990.0  2015-07-01T13:00:00.000000Z
4           T2  2862.0  2015-07-01T14:00:00.000000Z
...        ...     ...                          ...
1491        

In [9]:
import plotly.express as px

# Create a Plotly figure
fig = px.line(series, x='ds', y='values', title=id, labels={'ds': 'Date', 'values': 'Values'})

# Update layout for better readability
fig.update_layout(
    xaxis_title='Date',
    yaxis_title='Values',
    xaxis=dict(showgrid=True, tickangle=45),
    yaxis=dict(showgrid=True),
    template='plotly_dark'
)

# Show the figure
fig.show()

# Temporal Agents

- StatisticalForecast
- NeuralForecast
- FoundationalForecast
- ForecastCombination
- ForecastReconciliation
- CodeExecutor



In [2]:
import numpy as np

class GaussianReconciliation:
    def __init__(self, Sct, covariance_matrix):
        """
        Initialize the Gaussian reconciliation with structural matrix Sct and covariance matrix.

        Parameters:
        - Sct: Cross-temporal structural matrix.
        - covariance_matrix: Covariance matrix of the base forecasts.
        """
        self.Sct = Sct
        self.covariance_matrix = covariance_matrix
        self.inv_covariance = np.linalg.inv(covariance_matrix)

    def reconcile_forecasts(self, base_forecasts):
        """
        Reconcile base forecasts using the projection matrix method.

        Parameters:
        - base_forecasts: Array of base forecasts (incoherent forecasts).

        Returns:
        - reconciled_forecasts: Reconciled forecasts.
        """
        # Calculate the projection matrix M
        Sct_cov_Sct_T_inv = np.linalg.inv(self.Sct @ self.inv_covariance @ self.Sct.T)
        M = self.Sct.T @ Sct_cov_Sct_T_inv @ self.Sct @ self.inv_covariance
        
        # Reconcile the forecasts
        reconciled_forecasts = M @ base_forecasts
        return reconciled_forecasts

    def reconcile_covariance(self):
        """
        Compute the reconciled covariance matrix.

        Returns:
        - reconciled_covariance: Reconciled covariance matrix.
        """
        # Calculate the projection matrix M
        Sct_cov_Sct_T_inv = np.linalg.inv(self.Sct @ self.inv_covariance @ self.Sct.T)
        M = self.Sct.T @ Sct_cov_Sct_T_inv @ self.Sct @ self.inv_covariance
        
        # Reconcile the covariance matrix
        reconciled_covariance = M @ self.covariance_matrix @ M.T
        return reconciled_covariance

# Example Usage
# Assume Sct is the structural matrix, covariance_matrix is the covariance matrix of base forecasts, 
# and base_forecasts is the vector of base forecasts.

# Update the structural matrix to match the dimensionality of the problem
Sct = np.array([[1, 0, 1], [0, 1, 1], [1, 1, 0]])  # Updated structural matrix
covariance_matrix = np.array([[1.0, 0.5, 0.3], [0.5, 1.0, 0.2], [0.3, 0.2, 1.0]])  # Covariance matrix
base_forecasts = np.array([100, 200, 300])  # Base forecasts

# Create the reconciliation object
reconciliation = GaussianReconciliation(Sct, covariance_matrix)

# Get the reconciled forecasts
reconciled_forecasts = reconciliation.reconcile_forecasts(base_forecasts)
reconciled_covariance = reconciliation.reconcile_covariance()

print("Reconciled Forecasts:", reconciled_forecasts)
print("Reconciled Covariance Matrix:\n", reconciled_covariance)


Reconciled Forecasts: [100. 200. 300.]
Reconciled Covariance Matrix:
 [[1.  0.5 0.3]
 [0.5 1.  0.2]
 [0.3 0.2 1. ]]


In [3]:
Sct

array([[1, 0, 1],
       [0, 1, 1],
       [1, 1, 0]])

In [4]:
base_forecasts

array([100, 200, 300])

In [5]:
covariance_matrix

array([[1. , 0.5, 0.3],
       [0.5, 1. , 0.2],
       [0.3, 0.2, 1. ]])